### PR TITLE
Try the theoretical MAX even if the next pps is lower than the resolution.

### PR DESCRIPTION
**Pull request by msaitoh**
This change resolve the problem that the RFC2544 test don't try the
theoretical MAX pps and report the percentage with 99.9%.

Before:
```
ipgen -T ix0,172.16.0.2,172.16.0.1/24 -R ix1,172.16.1.2,172.16.1.1/24 --rfc2544 --rfc2544-trial-duration 30 --rfc2544-tolerable-error-rate 0.1 --rfc2544-pps-resolution 0.02 --rfc2544-pktsize 46,110,238,494,1500 --flowlist flowlist-172_16_0_3-172_16_1_3-8-2flow.txt
(snip)
rfc2544 tolerable error rate: 0.1000%
rfc2544 trial duration: 30 sec
rfc2544 pps resolution: 0.0200%
rfc2544 interval: 0 sec
rfc2544 warming duration: 1 sec

framesize|0M  100M 200M 300M 400M 500M 600M 700M 800M 900M 1Gbps
---------+----+----+----+----+----+----+----+----+----+----+
      64 |##############                                      266.93Mbps,  521343/1488095pps,  35.03%
     128 |##############################                      581.08Mbps,  567462/ 844594pps,  67.19%
     256 |###############################################     927.42Mbps,  452843/ 452898pps,  99.99%
     512 |#################################################   962.29Mbps,  234934/ 234962pps,  99.99%
    1518 |##################################################  986.88Mbps,   81265/  81274pps,  99.99%

framesize|0   |100k|200k|300k|400k|500k|600k|700k|800k|900k|1.0m|1.1m|1.2m|1.3m|1.4m|1.5m pps
---------+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
      64 |##########################                                                  521343/1488095pps,  35.03%
     128 |############################                                                567462/ 844594pps,  67.19%
     256 |######################                                                      452843/ 452898pps,  99.99%
     512 |###########                                                                 234934/ 234962pps,  99.99%
    1518 |####                                                                         81265/  81274pps,  99.99%
```

After:
```
ipgen -T ix0,172.16.0.2,172.16.0.1/24 -R ix1,172.16.1.2,172.16.1.1/24 --rfc2544 --rfc2544-trial-duration 30 --rfc2544-tolerable-error-rate 0.1 --rfc2544-pps-resolution 0.02 --rfc2544-pktsize 46,110,238,494,1500 --flowlist flowlist-172_16_0_3-172_16_1_3-8-2flow.txt
(snip)
rfc2544 tolerable error rate: 0.1000%
rfc2544 trial duration: 30 sec
rfc2544 pps resolution: 0.0200%
rfc2544 interval: 0 sec
rfc2544 warming duration: 1 sec

framesize|0M  100M 200M 300M 400M 500M 600M 700M 800M 900M 1Gbps
---------+----+----+----+----+----+----+----+----+----+----+
      64 |##############                                      266.65Mbps,  520798/1488095pps,  35.00%
     128 |#############################                       570.84Mbps,  557461/ 844594pps,  66.00%
     256 |###############################################     927.54Mbps,  452898/ 452898pps, 100.00%
     512 |#################################################   962.40Mbps,  234962/ 234962pps, 100.00%
    1518 |##################################################  986.99Mbps,   81274/  81274pps, 100.00%

framesize|0   |100k|200k|300k|400k|500k|600k|700k|800k|900k|1.0m|1.1m|1.2m|1.3m|1.4m|1.5m pps
---------+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
      64 |##########################                                                  520798/1488095pps,  35.00%
     128 |###########################                                                 557461/ 844594pps,  66.00%
     256 |######################                                                      452898/ 452898pps, 100.00%
     512 |###########                                                                 234962/ 234962pps, 100.00%
    1518 |####                                                                         81274/  81274pps, 100.00%
```

Example output of ipgen-debug.log with DEBUG flag:
```
2024-05-23 17:41:57 measuring pktsize 1500, pps 81255->81265, 986.76->986.88Mbps [986.76Mbps:986.99Mbps]
2024-05-23 17:42:27 RFC2544: tx_underrun=0, pause_detect_threshold=10000, tx=2446039, tolerable_error_rate=0.1000
2024-05-23 17:42:27 RFC2544: The upperpps(81281) reached the theoretical MAX(81274). Try the theoretical MAX by ignoring the pps resolution
2024-05-23 17:42:27 RFC2544: pktsize=1500, pps=81274, no drop. up pps
2024-05-23 17:42:27 warming: 1 sec, pktsize 1500, pps 81274, 986.99Mbps [986.88Mbps:986.99Mbps]
2024-05-23 17:42:28 measuring pktsize 1500, pps 81265->81274, 986.88->986.99Mbps [986.88Mbps:986.99Mbps]
2024-05-23 17:42:58 RFC2544: tx_underrun=0, pause_detect_threshold=10000, tx=2446312, tolerable_error_rate=0.1000
2024-05-23 17:42:58 RFC2544: Theoretical MAX! (curpps=81274, limitpps=81274)
2024-05-23 17:42:58 done. pktsize 1500, maximum pps 81274 (986.99Mbps)

```

### CODE REVIEW

**Comment by ozaki-r** [comment]
The additional code looks quite exceptional.  So I prefer to put the code into an exceptional branch like this:

```
diff --git a/gen/gen.c b/gen/gen.c
index 4f07459..19a57f2 100644
--- a/gen/gen.c
+++ b/gen/gen.c
@@ -2897,9 +2897,29 @@ rfc2544_up_pps(void)
        struct rfc2544_work *work = &rfc2544_work[rfc2544_nthtest];
        unsigned int nextpps;
 
+       /* Theoretical MAX */
+       if (work->curpps == work->limitpps) {
+               DEBUGLOG("RFC2544: Theoretical MAX! (curpps=%d, limitpps=%d)\n", work->curpps, work->limitpps);
+               return 1;
+       }
 
-       if ((work->curpps + work->ppsresolution - 1) >= work->maxpps)
+       if ((work->curpps + work->ppsresolution) > work->maxpps) {
+               if ((work->curpps + work->ppsresolution) >= work->limitpps) {
+                       /*
+                        * The upperpps reached the theoretical MAX. Try the theoretical MAX by ignoring the
+                        * pps resolution.
+                        */
+                       DEBUGLOG("RFC2544: The upperpps(%d) reached the theoretical MAX(%d). Try the theoretical MAX by ignoring the pps resolution\n",
+                           upperpps, work->limitpps);
+                       work->prevpps = work->curpps;
+                       work->minpps = work->curpps;
+                       work->curpps = work->limitpps;
+                       return 0;
+               }
+               DEBUGLOG("RFC2544: lower than pps resolution (curpps=%d, limitpps=%d, upperpps=%d)\n",
+                   work->curpps, work->limitpps, upperpps);
                return 1;
+       }
 
        work->prevpps = work->curpps;
        work->minpps = work->curpps;


```

**Comment by msaitoh** [comment]
Tested with/without DEBUG option.

```
2024-05-27 14:43:56 warming: 1 sec, pktsize 494, pps 234934, 962.29Mbps [962.17Mbps:962.40Mbps]
2024-05-27 14:43:57 measuring pktsize 494, pps 234905->234934, 962.17->962.29Mbps [962.17Mbps:962.40Mbps]
2024-05-27 14:44:27 RFC2544: tx_underrun=0, pause_detect_threshold=10000, tx=7059767, tolerable_error_rate=0.1000
2024-05-27 14:44:27 RFC2544: New upperbound(234980) reached the theoretical MAX(234962). Try the theoretical MAX by ignoring the pps resolution
2024-05-27 14:44:27 RFC2544: pktsize=494, pps=234962, no drop. up pps
2024-05-27 14:44:27 warming: 1 sec, pktsize 494, pps 234962, 962.40Mbps [962.29Mbps:962.40Mbps]
2024-05-27 14:44:28 measuring pktsize 494, pps 234934->234962, 962.29->962.40Mbps [962.29Mbps:962.40Mbps]
2024-05-27 14:44:58 RFC2544: tx_underrun=0, pause_detect_threshold=10000, tx=7072356, tolerable_error_rate=0.1000
2024-05-27 14:44:58 RFC2544: Theoretical MAX! (curpps=234962, limitpps=234962)
2024-05-27 14:44:58 done. pktsize 494, maximum pps 234962 (962.40Mbps)
```

**Review by ozaki-r — APPROVED** [review]
LGTM

**Comment by ozaki-r** [comment]
Thank you for the effort 👍

**Pull request merged**
